spring:
  datasource:
    url: jdbc:postgresql://db:5432/order-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  rabbitmq:
    host: rabbitmq
    queue: queue
    port: 5672
    username: guest
    password: guest
